version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: RecipeDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/RecipeProject.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=RecipeDb;Username=user;Password=1234
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:

