services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: RecipeDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./src/RecipeProject.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=RecipeDb;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: